// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://stqgyezgboqmenniwikf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN0cWd5ZXpnYm9xbWVubml3aWtmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4MzEwMzcsImV4cCI6MjA2ODQwNzAzN30.p19EH8kIsA1YIQNYylaTRmDO40f31RykdaT0JbvQpEM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Clear out any leftover sample data on first real login
supabase.auth.onAuthStateChange((event, session) => {
  if (event === 'SIGNED_IN' && session?.user) {
    const uid = session.user.id;
    supabase.from('categories').delete().neq('user_id', uid);
    supabase.from('transactions').delete().neq('user_id', uid);
    supabase.from('budgets').delete().neq('user_id', uid);
  }
});
